### ISSUE TITLE
prefix observatory metrics

### ISSUE THREAD

**Issue by fortytw2** [Jimdo/observatory-exporter#1]
would be wonderful if the exported metrics were something like `observatory_*` per https://prometheus.io/docs/practices/naming/ - helps a lot when you have a large number of metrics

**Comment by shartmnn** [comment]
Hey @fortytw2, thanks for reporting! :)

The namespace 'observatory' gets passed to the prometheus.Desc which gets used when calling MustNewConstMetric. 
See: https://github.com/Jimdo/observatory-exporter/blob/master/exporter.go#L24
https://github.com/Jimdo/observatory-exporter/blob/master/exporter.go#L56

That should do already what you're asking for. I am able to query our prometheus server that way and see the observatory_ 'prefix'..

**Comment by fortytw2** [comment]
fantastic, @shartmnn - I was a bit confused in the readme, here https://github.com/Jimdo/observatory-exporter#exposed-metrics (haven't given it a spin yet, either :s)

**Comment by shartmnn** [comment]
I updated the readme. The metrics names now include the namespace/prefix.

https://github.com/Jimdo/observatory-exporter/commit/631d7ca98991402fe3a8fba4cc58130f7c14b812

Good catch!

**Comment by fortytw2** [comment]
sweet! :smile:
