### ISSUE TITLE
How often does it query Mozilla Observatory

### ISSUE THREAD

**Issue by brunoqc** [Jimdo/observatory-exporter#2]
Does it query Mozilla Observatory every time prometheus fetch the data?

**Comment by smon** [comment]
Sorry for the late response. 

It does query observatory in a fixed interval, that you can specify via the command line parameter 'observatory.interval' (in seconds) - see https://github.com/Jimdo/observatory-exporter/blob/master/observatory_exporter.go#L46

The default is currently 60 minutes. There is also a rate limiting from the Observatory API itself in place that you can't query a page more than once every 3 minutes, see: https://github.com/mozilla/tls-observatory#post-/api/v1/scan

**Comment by brunoqc** [comment]
Thanks!
